package o;

import com.netflix.mediaclient.StatusCode;
import com.netflix.mediaclient.android.app.NetflixImmutableStatus;

/* renamed from: o.Nw  reason: case insensitive filesystem */
/* loaded from: classes.dex */
public interface InterfaceC1078Nw {
    public static final NetflixImmutableStatus B;
    public static final NetflixImmutableStatus D;
    public static final NetflixImmutableStatus E;
    public static final NetflixImmutableStatus H;
    public static final NetflixImmutableStatus L;
    public static final NetflixImmutableStatus O;
    public static final NetflixImmutableStatus P;
    public static final NetflixImmutableStatus Q;
    public static final NetflixImmutableStatus R;
    public static final NetflixImmutableStatus S;
    public static final NetflixImmutableStatus T;
    public static final NetflixImmutableStatus W;
    public static final NetflixImmutableStatus a;
    public static final NetflixImmutableStatus aA;
    public static final NetflixImmutableStatus aB;
    public static final NetflixImmutableStatus aF;
    public static final NetflixImmutableStatus aH;
    public static final NetflixImmutableStatus aI;
    public static final NetflixImmutableStatus aK;
    public static final NetflixImmutableStatus aL;
    public static final NetflixImmutableStatus aM;
    public static final NetflixImmutableStatus aN;
    public static final NetflixImmutableStatus aO;
    public static final NetflixImmutableStatus aQ;
    public static final NetflixImmutableStatus aT;
    public static final NetflixImmutableStatus aU;
    public static final NetflixImmutableStatus ad;
    public static final NetflixImmutableStatus ae;
    public static final NetflixImmutableStatus af;
    public static final NetflixImmutableStatus ag;
    public static final NetflixImmutableStatus ah;
    public static final NetflixImmutableStatus ai;
    public static final NetflixImmutableStatus aj;
    public static final NetflixImmutableStatus ak;
    public static final NetflixImmutableStatus al;
    public static final NetflixImmutableStatus am;
    public static final NetflixImmutableStatus an;
    public static final NetflixImmutableStatus ao;
    public static final NetflixImmutableStatus ap;
    public static final NetflixImmutableStatus aq;
    public static final NetflixImmutableStatus ar;
    public static final NetflixImmutableStatus as;
    public static final NetflixImmutableStatus at;
    public static final NetflixImmutableStatus au;
    public static final NetflixImmutableStatus av;
    public static final NetflixImmutableStatus aw;
    public static final NetflixImmutableStatus ax;
    public static final NetflixImmutableStatus ay;
    public static final NetflixImmutableStatus b;
    public static final NetflixImmutableStatus c;
    public static final NetflixImmutableStatus d;
    public static final NetflixImmutableStatus f;
    public static final NetflixImmutableStatus g;
    public static final NetflixImmutableStatus h;
    public static final NetflixImmutableStatus i;
    public static final NetflixImmutableStatus j;
    public static final NetflixImmutableStatus k;
    public static final NetflixImmutableStatus l;
    public static final NetflixImmutableStatus m;
    public static final NetflixImmutableStatus n;

    /* renamed from: o  reason: collision with root package name */
    public static final NetflixImmutableStatus f13379o;
    public static final NetflixImmutableStatus p;
    public static final NetflixImmutableStatus q;
    public static final NetflixImmutableStatus r;
    public static final NetflixImmutableStatus s;
    public static final NetflixImmutableStatus t;
    public static final NetflixImmutableStatus u;
    public static final NetflixImmutableStatus v;
    public static final NetflixImmutableStatus x;
    public static final NetflixImmutableStatus y;
    public static final NetflixImmutableStatus z;
    public static final NetflixImmutableStatus aJ = new NetflixImmutableStatus(StatusCode.OK);
    public static final NetflixImmutableStatus aE = new NetflixImmutableStatus(StatusCode.OBSOLETE_APP_VERSION);
    public static final NetflixImmutableStatus az = new NetflixImmutableStatus(StatusCode.NON_RECOMMENDED_APP_VERSION);
    public static final NetflixImmutableStatus w = new NetflixImmutableStatus(StatusCode.FORCED_TESTING_ERROR);
    public static final NetflixImmutableStatus aP = new NetflixImmutableStatus(StatusCode.UNKNOWN);
    public static final NetflixImmutableStatus aC = new NetflixImmutableStatus(StatusCode.NOT_VALID);
    public static final NetflixImmutableStatus e = new NetflixImmutableStatus(StatusCode.FALKOR_TASK_CANCELLED);
    public static final NetflixImmutableStatus aD = new NetflixImmutableStatus(StatusCode.NRD_ERROR);
    public static final NetflixImmutableStatus aG = new NetflixImmutableStatus(StatusCode.NO_CONNECTIVITY);
    public static final NetflixImmutableStatus A = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT);
    public static final NetflixImmutableStatus ac = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_PUSH);

    /* renamed from: J  reason: collision with root package name */
    public static final NetflixImmutableStatus f13378J = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_MDX);
    public static final NetflixImmutableStatus aa = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_PROBE);
    public static final NetflixImmutableStatus N = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_FALKOR);
    public static final NetflixImmutableStatus C = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_CDX);
    public static final NetflixImmutableStatus Z = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_ZUUL);
    public static final NetflixImmutableStatus ab = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_VOIP);
    public static final NetflixImmutableStatus Y = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_RESOURCES);
    public static final NetflixImmutableStatus V = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_OFFLINE);
    public static final NetflixImmutableStatus M = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_MONEYBALL);
    public static final NetflixImmutableStatus I = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_DIAGNOSIS);
    public static final NetflixImmutableStatus U = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_PRE_APP);
    public static final NetflixImmutableStatus G = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_ERROR);
    public static final NetflixImmutableStatus X = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_PLAYER);
    public static final NetflixImmutableStatus K = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_LOG);
    public static final NetflixImmutableStatus F = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_CONFIG_LOAD);

    static {
        StatusCode statusCode = StatusCode.INIT_SERVICE_TIMEOUT_CONFIG_FETCH;
        z = new NetflixImmutableStatus(statusCode);
        B = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_CONFIG_CREATE_CRYPTO);
        D = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_CONFIG_CREATE_ESN);
        H = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_CONFIG_FIND_DEVICE_ID);
        E = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_CONFIG_INIT_CRYPTO);
        L = new NetflixImmutableStatus(statusCode);
        W = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_MSL_LOAD);
        P = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_MSL_CREATE_CLIENT);
        O = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_MSL_CREATE_CONTEXT);
        T = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_MSL_LOAD_STORE);
        R = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_MSL_ESN_MIGRATION);
        S = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_MSL_ESN_MIGRATION_PING);
        Q = new NetflixImmutableStatus(StatusCode.INIT_SERVICE_TIMEOUT_MSL_APPBOOT);
        v = new NetflixImmutableStatus(StatusCode.ESN_MIGRATION_NO_CONNECTIVITY);
        y = new NetflixImmutableStatus(StatusCode.FATAL_CONFIG_BLACKLISTED);
        f = new NetflixImmutableStatus(StatusCode.DRM_FAILURE_CDM_GENERIC_ERROR);
        l = new NetflixImmutableStatus(StatusCode.DRM_FAILURE_CDM_NOT_PROVISIONED);
        s = new NetflixImmutableStatus(StatusCode.DRM_FAILURE_CDM_SERVER_DENIED);
        h = new NetflixImmutableStatus(StatusCode.DRM_FAILURE_CDM_EXCEPTION);
        g = new NetflixImmutableStatus(StatusCode.DRM_FAILURE_CDM_KEY_SET_EMPTY);
        n = new NetflixImmutableStatus(StatusCode.DRM_FAILURE_CDM_RESOURCE_BUSY);
        j = new NetflixImmutableStatus(StatusCode.DRM_FAILURE_CDM_LICENSE_EMPTY);
        r = new NetflixImmutableStatus(StatusCode.DRM_FAILURE_MEDIADRM_STATE_EXCEPTION);
        q = new NetflixImmutableStatus(StatusCode.DRM_FAILURE_MEDIADRM_RESET);
        aI = new NetflixImmutableStatus(StatusCode.USER_SIGNIN_FAILURE_TRY_SIGNUP);
        aN = new NetflixImmutableStatus(StatusCode.USER_NOT_AUTHORIZED);
        b = new NetflixImmutableStatus(StatusCode.BLADERUNNER_FAILURE);
        ax = new NetflixImmutableStatus(StatusCode.NODEQUARK_FAILURE);
        t = new NetflixImmutableStatus(StatusCode.DRM_FAILURE_GOOGLE_DECLINED_PROVISIONING);
        at = new NetflixImmutableStatus(StatusCode.MSL_LEGACY_CRYPTO);
        aA = new NetflixImmutableStatus(StatusCode.MSL_LEGACY_CRYPTO_BUT_USED_WIDEVINE_BEFORE);
        aw = new NetflixImmutableStatus(StatusCode.MSL_BLACKLISTED_DEVICE_FAILBACK);
        as = new NetflixImmutableStatus(StatusCode.MSL_BLACKLISTED_DEVICE_FATAL);
        an = new NetflixImmutableStatus(StatusCode.MSL_BAD_CHALLENGE);
        aq = new NetflixImmutableStatus(StatusCode.MSL_INVALID_KEY_REQUEST);
        aO = new NetflixImmutableStatus(StatusCode.WIDEVINE_L1_ALL_ZEROS_SIGNATURE_CHALLENGE);
        aQ = new NetflixImmutableStatus(StatusCode.WIDEVINE_L1_FAILURE_OS_UPGRADE);
        ap = new NetflixImmutableStatus(StatusCode.MSL_APPBOOT_RETRY_MAX_REACHED);
        ad = new NetflixImmutableStatus(StatusCode.INTERNAL_ERROR);
        af = new NetflixImmutableStatus(StatusCode.UI_RESET_INTERACTIVE_ERROR);
        aK = new NetflixImmutableStatus(StatusCode.INT_ERR_SERVICE_DISCONNECTED);
        ag = new NetflixImmutableStatus(StatusCode.INT_ERR_ADVIS_VIDEO_ID_NULL);
        ai = new NetflixImmutableStatus(StatusCode.INT_ERR_CMP_RESP_NULL);
        al = new NetflixImmutableStatus(StatusCode.INT_ERR_RESOURCE_URL_NULL);
        ah = new NetflixImmutableStatus(StatusCode.INT_ERR_CB_NULL);
        am = new NetflixImmutableStatus(StatusCode.INT_ERR_REALM_DETAILS_NULL);
        ak = new NetflixImmutableStatus(StatusCode.INT_ERR_MNGR_NOT_READY);
        ae = new NetflixImmutableStatus(StatusCode.INT_ERR_BAD_COOKIES);
        ar = new NetflixImmutableStatus(StatusCode.MANIFEST_PREFETCH_PROCESSING_ERROR);
        ao = new NetflixImmutableStatus(StatusCode.MANIFEST_PREFETCH_CANCELLED_BY_PLAYBACK);
        a = new NetflixImmutableStatus(StatusCode.API_REQUEST_UNSUCCESSFUL);
        m = new NetflixImmutableStatus(StatusCode.DRM_FAILURE_CDM_NO_LICENSE_RELEASE_ACK);
        aT = new NetflixImmutableStatus(StatusCode.WIDEVINE_PLUGIN_IN_BAD_STATE);
        d = new NetflixImmutableStatus(StatusCode.DEVICE_NOT_SUPPORTED);
        aF = new NetflixImmutableStatus(StatusCode.NO_PROFILES_FOUND);
        ay = new NetflixImmutableStatus(StatusCode.MSL_USER_ID_TOKEN_NOT_FOUND);
        aB = new NetflixImmutableStatus(StatusCode.MSL_SWITCH_PROFILE_BIND_FAIL);
        aU = new NetflixImmutableStatus(StatusCode.WIDEVINE_L1_NOT_SUPPORTED_WHEN_EXPECTED);
        aH = new NetflixImmutableStatus(StatusCode.PRIMARY_PROFILE_NOT_FOUND);
        au = new NetflixImmutableStatus(StatusCode.MSL_FAILED_TO_CREATE_CLIENT_NOT_SUPPORTED_CRYPTO);
        av = new NetflixImmutableStatus(StatusCode.MSL_FAILED_TO_CREATE_CLIENT_ON_APPBOOT);
        p = new NetflixImmutableStatus(StatusCode.DRM_FAILURE_GOOGLE_CDM_PROVISIONING_DENIED);
        i = new NetflixImmutableStatus(StatusCode.DRM_FAILURE_CDM_FAILED_TO_PROVIDE_PROVISION_RESPONSE);
        f13379o = new NetflixImmutableStatus(StatusCode.DRM_FAILURE_CDM_PROVISIONING_EMPTY);
        k = new NetflixImmutableStatus(StatusCode.DRM_FAILURE_CDM_PROVISIONING);
        c = new NetflixImmutableStatus(StatusCode.CREATE_SSO_TOKEN_FAILURE);
        aL = new NetflixImmutableStatus(StatusCode.RENEW_SSO_TOKEN_FAILURE);
        aj = new NetflixImmutableStatus(StatusCode.LOGOUT_FAILED);
        aM = new NetflixImmutableStatus(StatusCode.WIDEVINE_INITIAL_PROVISIONING_CHECK_FAILED);
        x = new NetflixImmutableStatus(StatusCode.DRM_FAILURE_MEDIA_SERVER_DIED);
        u = new NetflixImmutableStatus(StatusCode.DRM_FAILURE_NO_SESSION);
    }
}
