package androidx.media3.ui;

/* loaded from: classes2.dex */
public final class R {

    /* loaded from: classes2.dex */
    public static final class styleable {
        public static int AspectRatioFrameLayout_resize_mode;
        public static int[] AspectRatioFrameLayout = {com.netflix.mediaclient.R.attr.resize_mode};
        public static int[] Capability = {com.netflix.mediaclient.R.attr.queryPatterns, com.netflix.mediaclient.R.attr.shortcutMatchRequired};
        public static int[] ColorStateListItem = {16843173, 16843551, 16844359, com.netflix.mediaclient.R.attr.alpha, com.netflix.mediaclient.R.attr.lStar};
        public static int[] DefaultTimeBar = {com.netflix.mediaclient.R.attr.ad_marker_color, com.netflix.mediaclient.R.attr.ad_marker_width, com.netflix.mediaclient.R.attr.bar_gravity, com.netflix.mediaclient.R.attr.bar_height, com.netflix.mediaclient.R.attr.buffered_color, com.netflix.mediaclient.R.attr.played_ad_marker_color, com.netflix.mediaclient.R.attr.played_color, com.netflix.mediaclient.R.attr.scrubber_color, com.netflix.mediaclient.R.attr.scrubber_disabled_size, com.netflix.mediaclient.R.attr.scrubber_dragged_size, com.netflix.mediaclient.R.attr.scrubber_drawable, com.netflix.mediaclient.R.attr.scrubber_enabled_size, com.netflix.mediaclient.R.attr.touch_target_height, com.netflix.mediaclient.R.attr.unplayed_color};
        public static int[] FontFamily = {com.netflix.mediaclient.R.attr.fontProviderAuthority, com.netflix.mediaclient.R.attr.fontProviderCerts, com.netflix.mediaclient.R.attr.fontProviderFetchStrategy, com.netflix.mediaclient.R.attr.fontProviderFetchTimeout, com.netflix.mediaclient.R.attr.fontProviderPackage, com.netflix.mediaclient.R.attr.fontProviderQuery, com.netflix.mediaclient.R.attr.fontProviderSystemFontFamily};
        public static int[] FontFamilyFont = {16844082, 16844083, 16844095, 16844143, 16844144, com.netflix.mediaclient.R.attr.font, com.netflix.mediaclient.R.attr.fontStyle, com.netflix.mediaclient.R.attr.fontVariationSettings, com.netflix.mediaclient.R.attr.fontWeight, com.netflix.mediaclient.R.attr.ttcIndex};
        public static int[] GradientColor = {16843165, 16843166, 16843169, 16843170, 16843171, 16843172, 16843265, 16843275, 16844048, 16844049, 16844050, 16844051};
        public static int[] GradientColorItem = {16843173, 16844052};
        public static int[] LegacyPlayerControlView = {com.netflix.mediaclient.R.attr.ad_marker_color, com.netflix.mediaclient.R.attr.ad_marker_width, com.netflix.mediaclient.R.attr.bar_gravity, com.netflix.mediaclient.R.attr.bar_height, com.netflix.mediaclient.R.attr.buffered_color, com.netflix.mediaclient.R.attr.controller_layout_id, com.netflix.mediaclient.R.attr.played_ad_marker_color, com.netflix.mediaclient.R.attr.played_color, com.netflix.mediaclient.R.attr.repeat_toggle_modes, com.netflix.mediaclient.R.attr.scrubber_color, com.netflix.mediaclient.R.attr.scrubber_disabled_size, com.netflix.mediaclient.R.attr.scrubber_dragged_size, com.netflix.mediaclient.R.attr.scrubber_drawable, com.netflix.mediaclient.R.attr.scrubber_enabled_size, com.netflix.mediaclient.R.attr.show_fastforward_button, com.netflix.mediaclient.R.attr.show_next_button, com.netflix.mediaclient.R.attr.show_previous_button, com.netflix.mediaclient.R.attr.show_rewind_button, com.netflix.mediaclient.R.attr.show_shuffle_button, com.netflix.mediaclient.R.attr.show_timeout, com.netflix.mediaclient.R.attr.time_bar_min_update_interval, com.netflix.mediaclient.R.attr.touch_target_height, com.netflix.mediaclient.R.attr.unplayed_color};
        public static int[] PlayerControlView = {com.netflix.mediaclient.R.attr.ad_marker_color, com.netflix.mediaclient.R.attr.ad_marker_width, com.netflix.mediaclient.R.attr.animation_enabled, com.netflix.mediaclient.R.attr.bar_gravity, com.netflix.mediaclient.R.attr.bar_height, com.netflix.mediaclient.R.attr.buffered_color, com.netflix.mediaclient.R.attr.controller_layout_id, com.netflix.mediaclient.R.attr.played_ad_marker_color, com.netflix.mediaclient.R.attr.played_color, com.netflix.mediaclient.R.attr.repeat_toggle_modes, com.netflix.mediaclient.R.attr.scrubber_color, com.netflix.mediaclient.R.attr.scrubber_disabled_size, com.netflix.mediaclient.R.attr.scrubber_dragged_size, com.netflix.mediaclient.R.attr.scrubber_drawable, com.netflix.mediaclient.R.attr.scrubber_enabled_size, com.netflix.mediaclient.R.attr.show_fastforward_button, com.netflix.mediaclient.R.attr.show_next_button, com.netflix.mediaclient.R.attr.show_previous_button, com.netflix.mediaclient.R.attr.show_rewind_button, com.netflix.mediaclient.R.attr.show_shuffle_button, com.netflix.mediaclient.R.attr.show_subtitle_button, com.netflix.mediaclient.R.attr.show_timeout, com.netflix.mediaclient.R.attr.show_vr_button, com.netflix.mediaclient.R.attr.time_bar_min_update_interval, com.netflix.mediaclient.R.attr.touch_target_height, com.netflix.mediaclient.R.attr.unplayed_color};
        public static int[] PlayerView = {com.netflix.mediaclient.R.attr.ad_marker_color, com.netflix.mediaclient.R.attr.ad_marker_width, com.netflix.mediaclient.R.attr.animation_enabled, com.netflix.mediaclient.R.attr.artwork_display_mode, com.netflix.mediaclient.R.attr.auto_show, com.netflix.mediaclient.R.attr.bar_gravity, com.netflix.mediaclient.R.attr.bar_height, com.netflix.mediaclient.R.attr.buffered_color, com.netflix.mediaclient.R.attr.controller_layout_id, com.netflix.mediaclient.R.attr.default_artwork, com.netflix.mediaclient.R.attr.hide_during_ads, com.netflix.mediaclient.R.attr.hide_on_touch, com.netflix.mediaclient.R.attr.keep_content_on_player_reset, com.netflix.mediaclient.R.attr.played_ad_marker_color, com.netflix.mediaclient.R.attr.played_color, com.netflix.mediaclient.R.attr.player_layout_id, com.netflix.mediaclient.R.attr.repeat_toggle_modes, com.netflix.mediaclient.R.attr.resize_mode, com.netflix.mediaclient.R.attr.scrubber_color, com.netflix.mediaclient.R.attr.scrubber_disabled_size, com.netflix.mediaclient.R.attr.scrubber_dragged_size, com.netflix.mediaclient.R.attr.scrubber_drawable, com.netflix.mediaclient.R.attr.scrubber_enabled_size, com.netflix.mediaclient.R.attr.show_buffering, com.netflix.mediaclient.R.attr.show_shuffle_button, com.netflix.mediaclient.R.attr.show_subtitle_button, com.netflix.mediaclient.R.attr.show_timeout, com.netflix.mediaclient.R.attr.show_vr_button, com.netflix.mediaclient.R.attr.shutter_background_color, com.netflix.mediaclient.R.attr.surface_type, com.netflix.mediaclient.R.attr.time_bar_min_update_interval, com.netflix.mediaclient.R.attr.touch_target_height, com.netflix.mediaclient.R.attr.unplayed_color, com.netflix.mediaclient.R.attr.use_artwork, com.netflix.mediaclient.R.attr.use_controller};
        public static int[] RecyclerView = {16842948, 16842987, 16842993, com.netflix.mediaclient.R.attr.fastScrollEnabled, com.netflix.mediaclient.R.attr.fastScrollHorizontalThumbDrawable, com.netflix.mediaclient.R.attr.fastScrollHorizontalTrackDrawable, com.netflix.mediaclient.R.attr.fastScrollVerticalThumbDrawable, com.netflix.mediaclient.R.attr.fastScrollVerticalTrackDrawable, com.netflix.mediaclient.R.attr.layoutManager, com.netflix.mediaclient.R.attr.reverseLayout, com.netflix.mediaclient.R.attr.spanCount, com.netflix.mediaclient.R.attr.stackFromEnd};
    }
}
